"""
Pipeline module.
Executes the full RAG workflow completely decoupled from UI state.
"""

import logging
from src.config import settings
from src.embedder import embed_query
from src.retriever import hybrid_retrieve
from src.generator import generate_answer
from src.query_expander import expand_query
from src.guardrails import check_input, check_output
from src.evaluator import run_evaluation

logger = logging.getLogger(__name__)

def run_rag_pipeline(
    query: str,
    faiss_index,
    bm25_index,
    semantic_cache=None,
    use_guardrails: bool = True,
    use_cache: bool = True,
    use_query_expansion: bool = False,
    use_evaluation: bool = True,
    stream_callback=None
) -> dict:
    """
    Execute the full RAG pipeline:
    Guardrails → Cache → Query Expansion → Hybrid Retrieval → Reranking → Generation → Evaluation
    """
    pipeline_log = {"steps": []}

    # Step 1: Guardrails
    if use_guardrails:
        guard_result = check_input(query)
        if not guard_result.is_safe:
            return {
                "answer": f"⚠️ {guard_result.reason}",
                "sources": [],
                "model_used": "guardrails",
                "eval_scores": None,
                "from_cache": False,
                "pipeline_log": pipeline_log
            }
        query = guard_result.sanitized_query
        pipeline_log["steps"].append("✅ Guardrails passed")

    # Step 2: Generate query embedding
    query_emb = embed_query(query, settings.EMBEDDING_MODEL)

    # Step 3: Semantic Cache check
    if use_cache and semantic_cache:
        cached = semantic_cache.get(query, query_emb)
        if cached:
            pipeline_log["steps"].append("⚡ Cache hit!")
            cached["from_cache"] = True
            cached["pipeline_log"] = pipeline_log
            return cached

    # Step 4: Query Expansion (optional)
    queries = [query]
    if use_query_expansion:
        queries = expand_query(query)
        pipeline_log["steps"].append(f"🔄 Expanded to {len(queries)} queries")

    # Step 5: Hybrid Retrieval
    all_results = []
    if faiss_index and faiss_index.size > 0:
        for q in queries:
            q_emb = embed_query(q, settings.EMBEDDING_MODEL) if q != query else query_emb
            results = hybrid_retrieve(
                query=q,
                query_embedding=q_emb,
                faiss_index=faiss_index,
                bm25_index=bm25_index,
                top_k=settings.TOP_K_RETRIEVAL,
                rerank_top_n=settings.RERANK_TOP_N,
                reranker_model=settings.RERANKER_MODEL
            )
            all_results.extend(results)
        pipeline_log["steps"].append(f"🔍 Retrieved {len(all_results)} chunks")
    else:
        pipeline_log["steps"].append("⚠️ No documents indexed")

    # Deduplicate by chunk_id
    seen = set()
    unique_results = []
    for r in all_results:
        if r.chunk_id not in seen:
            seen.add(r.chunk_id)
            unique_results.append(r)

    # Take top N after dedup
    final_results = unique_results[:settings.RERANK_TOP_N]

    if not final_results:
        return {
            "answer": "I couldn't find any relevant information in the uploaded documents for your question. Please try rephrasing or upload more relevant documents.",
            "sources": [],
            "model_used": "none",
            "eval_scores": None,
            "from_cache": False,
            "pipeline_log": pipeline_log
        }

    # Step 6: LLM Generation
    pipeline_log["steps"].append("🤖 Generating answer...")
    gen_result = generate_answer(query, final_results, stream_callback=stream_callback)

    # Sanitize output
    if use_guardrails:
        gen_result.answer = check_output(gen_result.answer)

    pipeline_log["steps"].append(f"✅ Generated by {gen_result.model_used}")

    # Step 7: Evaluation (optional)
    eval_scores = None
    if use_evaluation and gen_result.answer:
        context_texts = [r.content for r in final_results]
        eval_scores = run_evaluation(query, gen_result.answer, context_texts)
        pipeline_log["steps"].append("📈 Evaluation complete")

    response = {
        "answer": gen_result.answer,
        "sources": gen_result.sources,
        "model_used": gen_result.model_used,
        "latency_ms": gen_result.latency_ms,
        "eval_scores": eval_scores,
        "from_cache": False,
        "pipeline_log": pipeline_log,
    }

    # Store in cache
    if use_cache and semantic_cache:
        semantic_cache.put(query, query_emb, response)

    return response
